Feature/#20 user profile
UniRegensburg/unsere-app-fur-die-universitat-regensburg-campus-guide pull request #78
Opened 2021-02-25 02:12 UTC by PascalLindemann

- First (minimal) version of user profile
- User can watch, access and edit (e.g. delete) his created and favorite routes
- User can watch (parts of) interesting statistics
- User can see personal information (as of now: the user name only)

- A possibility to change the user name via an AppBar Menu item is implemented but doesn't work yet (AppBar Menu does not appear)

2021-02-25 16:15 UTC, AndyGettingAn requested changes

2021-02-25 16:15 UTC, AndyGettingAn commented on app/src/main/java/de/ur/explure/views/CreatedRoutesFragment.kt
> +        adapter = RouteAdapter(this, this)
Vllt kannst du die ganze Adapter Initialisierung in eine extra `initializeAdapter()` Methode packen

2021-02-25 16:15 UTC, AndyGettingAn commented on app/src/main/java/de/ur/explure/views/CreatedRoutesFragment.kt
> +        builder.setTitle("ROUTE LÖSCHEN")
Jegliche Strings müssen in der string.xml gespeichert werden. Auch die im Code verwendeten. Du kannst auch Placeholder in der string.xml anlegen:

`<string name="my_string">My string name is %1$s</string>`

`String.format(getResources().getString(R.string.my_string), stringName)`

2021-02-25 16:15 UTC, AndyGettingAn commented on app/src/main/java/de/ur/explure/views/ProfileFragment.kt
> +    private fun showDialog() {
Wird der Code noch verwendet?

2021-02-25 16:15 UTC, AndyGettingAn commented on app/src/main/java/de/ur/explure/views/ProfileFragment.kt
> +const val HORIZONTAL_MARGIN_EDIT_TEXT = 32
Solche Konstanten sollten eig niemals im Code stehen. Wenn du sie aber trotzdem brauchst dann leg innerhalb der Klasse in `companion object`an:

```
class ProfileFragment : Fragment(R.layout.fragment_profile) {

   companion object {
       private const val VERTICAL_MARGIN_EDIT_TEXT = 8
       private const val HORIZONTAL_MARGIN_EDIT_TEXT = 32
  }
....
}

2021-03-02 18:20 UTC, michaelmeckl commented on app/src/main/java/de/ur/explure/views/ProfileFragment.kt
> +    ).toInt()
Solche Extension-Functions gehören eigentlich nicht in Fragments oder Activities, sondern in separate Files ausgelagert mit der Endung 'Ext', damit klar ist, dass es sich um von dir hinzugefügte Erweiterungen handelt.

2021-03-02 18:32 UTC, michaelmeckl commented on app/src/main/res/values/strings.xml
> +    <string name="remove_favorite_message_two"> should be removed from your favorites?</string>
Anstatt hier 2 Strings zu machen könntest du einfach einen [Stringplatzhalter ](https://developer.android.com/guide/topics/resources/string-resource#formatting-strings) verwenden. Z.B. 
`
<string name="remove_favorite_route_message"> Are you sure that the route %1$s should be removed from your favorites?</string>
`
Das gilt für einige andere Strings hier genauso.

2021-03-02 18:44 UTC, michaelmeckl commented on app/src/main/java/de/ur/explure/views/FavoriteRoutesFragment.kt
> +        dialog.show()
Die showDialog - Methode ist etwas umständlich. Das geht in Kotlin deutlich eleganter. Z.B. so (wenn du String-Templates verwendest):
```
with(MaterialAlertDialogBuilder(requireContext())) {
    setTitle(resources.getString(R.string.remove_favorite))
    setMessage(resources.getString(R.string.remove_favorite_route_message, route.title))
    setPositiveButton(resources.getString(R.string.yes)) { _, _ -> viewModel.removeRouteFromFavoriteRoutes(route) }
    setNegativeButton(resources.getString(R.string.no)) { _, _ -> }
    show()
}
```

2021-03-02 18:49 UTC, michaelmeckl commented on app/src/main/java/de/ur/explure/views/CreatedRoutesFragment.kt
> +        builder.setTitle(String.format(getResources().getString(R.string.delete_route)))
String.format(...) brauchst du nirgends. einfach nur `resources.getString(...)` reicht vollkommen. Auch mit String-Templates.

2021-03-21 16:47 UTC, michaelmeckl commented on app/src/main/java/de/ur/explure/views/ProfileFragment.kt
> +    }
Also der Code um das Profilbild zu updaten ist in jedem Fragment im Profil, das ist etwas redundant, aber auch nicht allzu schlimm.

2021-03-21 16:51 UTC, michaelmeckl commented on app/src/main/java/de/ur/explure/views/ProfileFragment.kt
> +    }
Die Methode sollte im userRepository aufgerufen werden, nicht im Fragment. Übergib die Parameter einfach durch das userViewModel ans Repository.

2021-03-21 17:12 UTC, michaelmeckl commented on app/src/main/java/de/ur/explure/views/ProfileFragment.kt
> +        startActivityForResult(intent, REQUEST_IMAGE_CAPTURE)
Das ist inzwischen soweit ich weiß deprecated (das sollte Android Studio dir auch anzeigen eigentlich). Intents aus Fragments sollten inzwischen mit der neuen [ActivityResultsContract - API ](https://developer.android.com/training/basics/intents/result)gemacht werden. [Hier ](https://wajahatkarim.com/2020/05/activity-results-api-onactivityresult/) ist ein sehr ausführliches Beispiel wie das geht (ganz unten auch direkt für Fotos). Aber verwende nicht zu viel Zeit das umzustellen, wenn es so ganz gut geht, reicht das im Moment auch.

2021-03-21 17:14 UTC, michaelmeckl requested changes
Ein paar Kleinigkeiten müssten noch angepasst werden, siehe Kommentare, ansonsten sieht's sehr gut aus. 
Eine Frage, weil ich das nirgends gesehen habe: Müssen fürs Aufnehmen von Bildern nicht Permissions abgefragt werden und im Manifest hinterlegt werden?

2021-03-21 17:25 UTC, michaelmeckl commented
> Ein paar Kleinigkeiten müssten noch angepasst werden, siehe Kommentare, ansonsten sieht's sehr gut aus.
> Eine Frage, weil ich das nirgends gesehen habe: Müssen fürs Aufnehmen von Bildern nicht Permissions abgefragt werden und im Manifest hinterlegt werden?

Nvm, permissions scheint man nur zu brauchen, wenn das auch gespeichert werden soll auf dem Gerät. Fürs Erste müsste es also so in Ordnung sein. Aber vielleicht sollte das hier noch ins Manifest? 

```
<uses-feature android:name="android.hardware.camera"
                  android:required="false" />
```
Vgl. offizielle Dokumentation zu Fotos: https://developer.android.com/training/camera/photobasics
Dann müsstest du vor deinem Kamera-Code aber noch mit ```hasSystemFeature(PackageManager.FEATURE_CAMERA_ANY)``` checken, ob eine Kamera vorhanden ist und ansonsten eine Warnung oder so anzeigen.

2021-03-25 07:56 UTC, michaelmeckl approved these changes

2021-03-25 08:05 UTC, AndyGettingAn approved these changes

2021-03-25 08:06 UTC, merged